server:
  port: 8081
 #This is a service. It has to register itself to eureka server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri : http://localhost:8080/realms/angu-project
  
